//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КалькуляторДляЛитейщиков.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VectorOrdersDBEntities2 : DbContext
    {
        public VectorOrdersDBEntities2()
            : base("name=VectorOrdersDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Продукции> Продукции { get; set; }
        public virtual DbSet<СоставПродукции> СоставПродукции { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СтатусЗаявки> СтатусЗаявки { get; set; }
        public virtual DbSet<СтатусСотрудника> СтатусСотрудника { get; set; }
        public virtual DbSet<ТипПродукции> ТипПродукции { get; set; }
        public virtual DbSet<ФотографияПродукции> ФотографияПродукции { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
    }
}
