//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КалькуляторДляЛитейщиков.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public int КодСтатусаЗаявки { get; set; }
        public int Количество { get; set; }
        public int КодПродукции { get; set; }
        public int КодСотрудника { get; set; }
    
        public virtual СоставПродукции СоставПродукции { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual СтатусЗаявки СтатусЗаявки { get; set; }
    }
}
