//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КалькуляторДляЛитейщиков.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукции
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукции()
        {
            this.СоставПродукции = new HashSet<СоставПродукции>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public int КодТипаПродукции { get; set; }
        public Nullable<int> КодФотографииПродукции { get; set; }
    
        public virtual ТипПродукции ТипПродукции { get; set; }
        public virtual ФотографияПродукции ФотографияПродукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродукции> СоставПродукции { get; set; }
    }
}
